name: ornekler
description: "A new Flutter Project."
publish_to: 'none'  # Bu proje özel olduğu için pub.dev'e yayınlamayı engelleyin.

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1  # API'den veri çekmek için gerekli HTTP kütüphanesi.
  provider: ^6.0.0  # State management için provider kütüphanesi.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Aşağıdaki yorum satırları, dökümantasyon için ek bilgiler içermektedir ve gerektiğinde kullanılabilir:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a package.orgl/bütlerini te

  # Uygulamanıza özel font eklemek için örnek bir yapı:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
